- name: Gathering facts
  hosts: local
  connection: local
  tasks:
    - name: Print the ansible facts
      ansible.builtin.debug:
        # msg: "Printing ansible facts"
        msg: "{{ ansible_facts }}"

    - name: Check Whether the redhat id present or not
      ansible.builtin.debug:
        msg: "Yes, It is Redhat package manager"
      when: ansible_facts.os_family == "RedHat"

    - name: Check Whether the debian id present or not
      ansible.builtin.debug:
        msg: "Yes, It is Debian package manager"
      when: ansible_facts.os_family == "Debian"