- name: Demo on error handling
  hosts: local
  connection: local
  tasks:
    - name: Checking the user exist or not
      ansible.builtin.command: id roboshop
      register: user_output

    - name: print the output
      ansible.built.debug:
        msg: "{{ user_output }}"
