; Can mange group of servers in inventory file by giving the the private IP addressof the server.
[frontend]
192:78.98.10
192:78.98.11
192:78.98.12

[backend]
192:78.198.20
192:78.198.21
192:78.198.22

[roboshop-children]
frontend
backend