#Can mange group of servers in inventory file by giving the the private IP addressof the server.

#Independent server.
192.78.98.48
#Frontend group of servers.
[frontend]
192.78.98.45
192.78.98.46
192.78.98.47
#Backend group of servers.
[backend]
192.78.198.49
192.78.198.50
192.78.198.51

[roboshop-children] 
frontend
backend